# Any PR opened, build images and run tests
name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOCKER_ORG: pangeo
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [base-notebook, pangeo-notebook, ml-notebook, pytorch-notebook, forge]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build base-image
      uses: docker/build-push-action@v3
      with:
        context: base-image
        with:
          driver-opts: network=host
        tags: pangeo/base-image:PR

    - name: Build Only
      uses: docker/build-push-action@v3
      with:
        context: ${{ matrix.IMAGE }}
        with:
          driver-opts: network=host
        tags: |
          localhost:5000/${{env.DOCKER_ORG}}/${{ matrix.IMAGE }}:PR
        build-args: | 
          PANGEO_BASE_IMAGE_TAG=PR

    - name: Report Image Size and Conda Packages
      run: |
        docker images
        docker run localhost:5000/${DOCKER_ORG}/${{ matrix.IMAGE }}:PR conda list --export

    - name: Test Image
      run: |
        docker run -u 1000 -w /srv/test -v $PWD:/srv/test localhost:5000/${DOCKER_ORG}/${{ matrix.IMAGE }}:PR ./run_tests.sh ${{ matrix.IMAGE }}
